name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java (corretto@17)
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build and test project
        run: sbt 'test'

      # https://github.com/marketplace/actions/github-tag-bump
      - name: Bump version and push tag
        if: github.event_name != 'pull_request'
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Build docker image, integration test, whatever
        run: sbt 'Docker / publishLocal'

  publish:
    name: Publish Artifacts
    needs: [build]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: publish to ECR
        shell: bash
        run: |
          echo "Placeholder for push to ECR"
          sbt 'show ThisBuild / version'
