name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-cov:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - run: echo "Some coverage report..."

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  ci-pass:
    runs-on: ubuntu-latest
    if: always()

    needs:
      - code-cov
      - build

    outputs:
      failure: ${{ steps.all-greens.outputs.failure }}
      result: ${{ steps.all-greens.outputs.result }}
      success: ${{ steps.all-greens.outputs.success }}

    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@849fa99e61aeb70b020dfebaae51d2f559753bcc
        with:
          allowed-skips: code-cov
          jobs: ${{ toJSON(needs) }}
        id: all-greens
      - run: |
          echo "failure: ${{ steps.all-greens.outputs.failure }}"
          echo "result: ${{ steps.all-greens.outputs.result }}"
          echo " success: ${{ steps.all-greens.outputs.success }}"

  cd:
    runs-on: ubuntu-latest

    needs: ci-pass
    if: github.event_name == 'pull_request' && needs.ci-pass.outputs.success

    steps:
      - run: echo "Release the kraken..."
