on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  do-the-needful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $(date +"%Y-%m-%d %H:%M:%S") >> dummy.txt
