name: Pull Request Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: crunchbase-infra
    timeout-minutes: 5
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "#(major|minor|patch|none): .*"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: false
          on-failed-regex-request-changes: false
          on-failed-regex-comment: "PR title must follow the regex: `%regex%`"
          on-succeeded-regex-dismiss-review-comment: ""

