name: releaser

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new_release_published }}
      new-release-version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 24
          dry_run: ${{ inputs.dry-run }}
          extra_plugins: |
            conventional-changelog-conventionalcommits

      - name: Do something when a new release published
        #if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "${{ steps.semantic.outputs.new_release_published }}"
          echo "${{ steps.semantic.outputs.new_release_version }}"

  call:
    if: ${{ needs.release.outputs.new-release-published }}
    permissions:
      contents: read
      id-token: write
    needs:
      - release
    uses: ./.github/workflows/release3.yml
    with:
      version: ${{ needs.release.outputs.new-release-version }}
      dry-run: ${{ inputs.dry-run }}

