name: releaser

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean

jobs:
  do-the-needful:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #- uses: actions/checkout@v4
      - if: inputs.dry-run
        uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: dry-${{ github.ref }}

      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 24
          dry_run: ${{ inputs.dry-run }}
          extra_plugins: |
            conventional-changelog-conventionalcommits
          branches: |
            ['${{ steps.branch.outputs.name }}']

     - name: Do something when a new release published
       #if: steps.semantic.outputs.new_release_published == 'true'
       run: |
         echo "${{ steps.semantic.outputs.new_release_published }}"
         echo "${{ steps.semantic.outputs.new_release_version }}"

     - uses: dawidd6/action-delete-branch@v3
       with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branches: dry-${{ github.ref }}
